/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'diary-entries': DiaryEntry;
    'pastoral-visits': PastoralVisit;
    'gallery-images': GalleryImage;
    'biography-sections': BiographySection;
    'featured-videos': FeaturedVideo;
    'appointment-slots': AppointmentSlot;
    'appointment-bookings': AppointmentBooking;
    'newsletter-editions': NewsletterEdition;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'diary-entries': DiaryEntriesSelect<false> | DiaryEntriesSelect<true>;
    'pastoral-visits': PastoralVisitsSelect<false> | PastoralVisitsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'biography-sections': BiographySectionsSelect<false> | BiographySectionsSelect<true>;
    'featured-videos': FeaturedVideosSelect<false> | FeaturedVideosSelect<true>;
    'appointment-slots': AppointmentSlotsSelect<false> | AppointmentSlotsSelect<true>;
    'appointment-bookings': AppointmentBookingsSelect<false> | AppointmentBookingsSelect<true>;
    'newsletter-editions': NewsletterEditionsSelect<false> | NewsletterEditionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    programme: Programme;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    programme: ProgrammeSelect<false> | ProgrammeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Controls which admin-tools pages and server actions this user can use. Admin = unrestricted; Newsletter editor = only the monthly Pastoral Diary editor + send pipeline.
   */
  role: 'admin' | 'newsletter_editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Recent engagements shown on the homepage. The latest three published entries (sorted by date, newest first) appear in the 'Recent Engagements' section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diary-entries".
 */
export interface DiaryEntry {
  id: number;
  title: string;
  date: string;
  location?: string | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Timeline of pastoral visits shown on /pastoral-visits, sorted by date (newest first). Use 'parish' for the place line and 'summary' for the purpose.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pastoral-visits".
 */
export interface PastoralVisit {
  id: number;
  title: string;
  date: string;
  parish?: string | null;
  deanery?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photographs displayed on /photo-gallery, ordered by the 'order' field (lower numbers first). Add a caption — it serves as alt text for accessibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  caption: string;
  category?: ('liturgical' | 'pastoral' | 'portraits' | 'episcopal' | 'vatican') | null;
  order?: number | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biography-sections".
 */
export interface BiographySection {
  id: number;
  heading: string;
  eyebrow?: string | null;
  order?: number | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pastoral videos shown in the homepage 'Pastoral Activities in Motion' grid. Up to nine entries are rendered, ordered by the 'order' field (lower first).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos".
 */
export interface FeaturedVideo {
  id: number;
  title: string;
  /**
   * The 11-character video ID from the YouTube URL — e.g. 'ZbrwZq-54hI' from https://youtu.be/ZbrwZq-54hI. Do NOT paste the full URL.
   */
  youtubeId: string;
  /**
   * Small uppercase eyebrow above the title, e.g. 'Sacred Orders · Onitsha'.
   */
  occasion?: string | null;
  /**
   * Optional — formatted as 'Month Year' on the tile. Leave blank if no specific date applies.
   */
  date?: string | null;
  /**
   * Optional, e.g. '1:12:40'. Shows in the bottom-right corner of the tile.
   */
  duration?: string | null;
  /**
   * Lower numbers appear first in the grid. Use the same number for ties; ties resolve by creation order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each row is a single bookable time window. Lay faithful book Tuesday slots; priests & religious book Wednesday slots. Set status to 'blocked' to hide a slot without deleting it (e.g. when His Grace is travelling).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-slots".
 */
export interface AppointmentSlot {
  id: number;
  label?: string | null;
  /**
   * Tuesday for lay faithful, Wednesday for priests & religious.
   */
  date: string;
  /**
   * 24-hour, HH:MM format (e.g. 09:00).
   */
  startTime: string;
  /**
   * 24-hour, HH:MM format (e.g. 09:30).
   */
  endTime: string;
  audience: 'laity' | 'clergy';
  /**
   * 'Available' means visitors can book it. 'Booked' is set automatically when a booking is made. 'Blocked' hides the slot from visitors without removing it.
   */
  status: 'available' | 'booked' | 'blocked';
  updatedAt: string;
  createdAt: string;
}
/**
 * Bookings made through the storefront. To cancel a booking on behalf of the visitor (e.g. when His Grace is travelling), set its status to 'Cancelled' and save — the slot is released and the visitor receives a polite cancellation email automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-bookings".
 */
export interface AppointmentBooking {
  id: number;
  /**
   * The reserved slot.
   */
  slot: number | AppointmentSlot;
  /**
   * Auto-set from the slot at booking time.
   */
  audience: 'laity' | 'clergy';
  fullName: string;
  email: string;
  phone?: string | null;
  /**
   * Parish (lay) or assignment (clergy).
   */
  parish?: string | null;
  reason: string;
  status: 'confirmed' | 'cancelled' | 'completed' | 'no-show';
  /**
   * Random token used in the cancellation link sent to the visitor.
   */
  confirmationCode: string;
  /**
   * Office-only — notes about the visitor or the meeting. Never shown to the visitor.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Monthly Pastoral Diary editions. Drafts are auto-generated on the 28th by the cron. Review posts, edit copy if needed, set status to 'Ready to send (approved)', then trigger the send from /admin-tools/send-newsletter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-editions".
 */
export interface NewsletterEdition {
  id: number;
  /**
   * The first day of the month this edition covers. e.g. 1 May 2026 for the May 2026 edition.
   */
  editionDate: string;
  /**
   * Auto-derived from editionDate (e.g. 'may-2026'). Editable but uniqueness is enforced.
   */
  slug: string;
  /**
   * The email subject. e.g. 'Pastoral Diary · May 2026'.
   */
  subjectLine: string;
  /**
   * Small uppercase label above the heading, e.g. 'PASTORAL DIARY · MMXXVI · MAY'.
   */
  eyebrow?: string | null;
  /**
   * Italic subhead under the display heading. One short sentence describing what this month's diary covers.
   */
  lead?: string | null;
  /**
   * Posts pulled from the FB page (chronological). The first post is the lead — it gets the full-bleed photo treatment.
   */
  posts?:
    | {
        /**
         * Facebook post id (for de-duplication).
         */
        fbPostId?: string | null;
        /**
         * Public Facebook permalink to the post.
         */
        permalinkUrl?: string | null;
        createdTime: string;
        /**
         * Post text from the FB caption. Edited copy is OK — this is what readers will see in the email.
         */
        message?: string | null;
        /**
         * Raw FB caption as fetched, preserved so 'Reset to original' and 'Rewrite editorially' can both reference it. Read-only.
         */
        originalMessage?: string | null;
        /**
         * Permanent image URL (mirrored from FB to Vercel Blob). Empty if the post has no image.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Final HTML rendered at send-time. Read-only — populated by the send action.
   */
  htmlSnapshot?: string | null;
  status: 'draft' | 'ready_to_send' | 'sending' | 'sent' | 'failed' | 'skipped_no_posts';
  /**
   * Resend Broadcast id, set on first successful create call.
   */
  resendBroadcastId?: string | null;
  sentAt?: string | null;
  /**
   * Audience size at send-time.
   */
  sentCount?: number | null;
  failedCount?: number | null;
  /**
   * Structured errors logged during draft creation or send.
   */
  errors?:
    | {
        at: string;
        kind: string;
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'diary-entries';
        value: number | DiaryEntry;
      } | null)
    | ({
        relationTo: 'pastoral-visits';
        value: number | PastoralVisit;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'biography-sections';
        value: number | BiographySection;
      } | null)
    | ({
        relationTo: 'featured-videos';
        value: number | FeaturedVideo;
      } | null)
    | ({
        relationTo: 'appointment-slots';
        value: number | AppointmentSlot;
      } | null)
    | ({
        relationTo: 'appointment-bookings';
        value: number | AppointmentBooking;
      } | null)
    | ({
        relationTo: 'newsletter-editions';
        value: number | NewsletterEdition;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diary-entries_select".
 */
export interface DiaryEntriesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  location?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pastoral-visits_select".
 */
export interface PastoralVisitsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  parish?: T;
  deanery?: T;
  summary?: T;
  body?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  caption?: T;
  category?: T;
  order?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biography-sections_select".
 */
export interface BiographySectionsSelect<T extends boolean = true> {
  heading?: T;
  eyebrow?: T;
  order?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos_select".
 */
export interface FeaturedVideosSelect<T extends boolean = true> {
  title?: T;
  youtubeId?: T;
  occasion?: T;
  date?: T;
  duration?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-slots_select".
 */
export interface AppointmentSlotsSelect<T extends boolean = true> {
  label?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  audience?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-bookings_select".
 */
export interface AppointmentBookingsSelect<T extends boolean = true> {
  slot?: T;
  audience?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  parish?: T;
  reason?: T;
  status?: T;
  confirmationCode?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-editions_select".
 */
export interface NewsletterEditionsSelect<T extends boolean = true> {
  editionDate?: T;
  slug?: T;
  subjectLine?: T;
  eyebrow?: T;
  lead?: T;
  posts?:
    | T
    | {
        fbPostId?: T;
        permalinkUrl?: T;
        createdTime?: T;
        message?: T;
        originalMessage?: T;
        imageUrl?: T;
        id?: T;
      };
  htmlSnapshot?: T;
  status?: T;
  resendBroadcastId?: T;
  sentAt?: T;
  sentCount?: T;
  failedCount?: T;
  errors?:
    | T
    | {
        at?: T;
        kind?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Editable copy on the homepage hero, daily reflection block, and pull-quote section. The Archbishop's name itself is not editable here — it is part of the brand mark.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Small uppercase label above the name, e.g. 'His Grace · Most Reverend'.
   */
  heroEyebrow?: string | null;
  /**
   * Reserved. The Archbishop's name is rendered as a brand mark and is not editable from here.
   */
  heroHeading?: string | null;
  /**
   * Italic line under the name. Year markers in the prose are kept as plain text.
   */
  heroSubheading?: string | null;
  /**
   * Replaces /hero.avif on the homepage. Leave empty to keep the default photo.
   */
  heroImage?: (number | null) | Media;
  /**
   * Rotating quote shown in the bone band. The date stamp updates automatically — only the quote text is editable here.
   */
  dailyReflection?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Centred large quote shown near the bottom of the page.
   */
  featuredQuote?: string | null;
  /**
   * e.g. '— Most Rev. Valerian M. Okeke'.
   */
  featuredQuoteAttribution?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The Pastoral Programme rendered on /diary. Add an entry per Mass, visit, ordination, or meeting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme".
 */
export interface Programme {
  id: number;
  /**
   * One row per engagement. Storefront category is derived from the title (Mass / Pastoral Visit / Meeting / Ordination / Retreat / Special); colour-coded automatically.
   */
  upcoming?:
    | {
        date: string;
        title: string;
        location?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroSubheading?: T;
  heroImage?: T;
  dailyReflection?: T;
  featuredQuote?: T;
  featuredQuoteAttribution?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme_select".
 */
export interface ProgrammeSelect<T extends boolean = true> {
  upcoming?:
    | T
    | {
        date?: T;
        title?: T;
        location?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}